general_settings:
  ## MANDATORY. Name of your photoprism docker container. You should have the container named: photoprism
  photoprism_container_name: <INSERT YOUR PHOTOPRISM CONTAINER NAME HERE>

## DELETE THE ONE YOU DON'T NEED. This is the schedule when you want the script to run and call the Reindexing command
backup_schedule:
  ## DELETE IF NOT NEEDED
  weekly:
    ## available values are MON, TUE, WED, THU, FRI, SAT, SUN.
    day: <INPUT DAY HERE>
    ## Use HH:mm format and wrap the time in quatation marks e.g. "14:28"
    time: <HH:mm>
  ## DELETE IF NOT NEEDED
  daily:
    ## Use HH:mm format and wrap the time in quatation marks e.g. "14:28"
    time: <HH:mm>
  ## DELETE IF NOT NEEDED. This schedule will run the preview generation command, on the specified day on the last week of the current month
  last_day_of_month:
    ## available values are MON, TUE, WED, THU, FRI, SAT, SUN.
    day: <INPUT DAY HERE>
    ## Use HH:mm format and wrap the time in quatation marks e.g. "14:28"
    time: <HH:mm>